In [7]:
import pandas as pd
import numpy as np

In [8]:
# Write a function so that the columns of the output matrix are powers of the input vector.

In [9]:
a = np.array ([1,2,4,6])
increasing = True

In [10]:
#np.column_stack([a**(power-1-i) for i in range(power)])

In [11]:
def custom_Vandermonde(x, increasing):
    power = len(a)
    if not increasing:
        return np.column_stack([x**(power-1-i) for i in range(power)])
    else:
        return np.column_stack([x**i for i in range(power)])

In [12]:
custom_Vandermonde(a,increasing)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   4,  16,  64],
       [  1,   6,  36, 216]], dtype=int32)

In [13]:
increasing = False

In [14]:
custom_Vandermonde(a,increasing)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [216,  36,   6,   1]], dtype=int32)

In [15]:
# Write a function to find moving average in an array over a window
np.set_printoptions(precision = 2)


In [16]:
b = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [17]:
b

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [18]:
n = 3

In [19]:
def movingAvg(x,n):
    cumsum = np.cumsum(np.insert(x,0,0)) 
    return (cumsum[n:] - cumsum[:-n]) / n
movingAvg(b,n)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])

In [20]:
def movingAvgg(x,n):
    list = []
    arr = np.array(list)
    for i in range(len(x)-n+1):
        list.append(np.sum(x[i:n+i]) / n)
    return np.array(list)
movingAvgg(b,n)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])